name: Comment on Issue from Commit

on:
  push:
    branches:
      - main  # ←必要に応じて変更 (develop など)

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment on related Issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commits = context.payload.commits;
            for (const commit of commits) {
              const matches = commit.message.match(/#(\d+)/g);
              if (!matches) continue;
              for (const match of matches) {
                const issue_number = parseInt(match.slice(1));
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number,
                  body: `自動コメント: コミットされました\n\n**${commit.message}**\n(${commit.url})`
                });
              }
            }
